name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev libssl-dev ccache git zip unzip openjdk-17-jdk python3-pip python3-venv autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake gettext

    - name: Install Buildozer in Virtual Env
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools
        pip install "cython<3.0.0" buildozer

    - name: Build APK
      run: |
        source venv/bin/activate
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: dukan_app_apk
        path: bin/*.apk
