name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev libssl-dev ccache git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake gettext libffi-dev libssl-dev

    - name: Build with Buildozer
      uses: ArtemSydoryk/buildozer-action@v1.2.0
      with:
        command: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: dukan_app_apk
        path: bin/*.apk
